name: Deploy Foundry Virtual Tabletop

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}

    - name: deploy
      uses: azure/arm-deploy@v1
      with:
        failOnStdErr: false
        parameters: >
          location=${{ vars.LOCATION }}
          resourceGroupName=${{ vars.RESOURCE_GROUP_NAME }}
        region: ${{ vars.LOCATION }}
        scope: subscription
        template: ./eng/deployment/main.bicep
